package model;

public enum MedicalSpecialty {
    DIGESTIVE_SYSTEM,
    CARDIOLOGY,
    GENERAL_SURGERY,
    DERMATOLOGY,
    INTERNAL_MEDICINE,
    ONCOLOGY,
    OPHTHALMOLOGY,
    PSYCHIATRY,
    TRAUMATOLOGY
}
